theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[editor.cursor-shape]
insert = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "separator", "diagnostics", "separator", "file-name"]
right = ["file-encoding", "separator", "file-type", "separator", "position-percentage", "separator", "position", "separator", "total-line-numbers"]